[project]
name = "orbit-wars-jw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kaggle-environments>=1.28.0",
    "tqdm>=4.67.3",
]

[tool.uv]
# pygame has no wheels for Python 3.14 — skip it (only needed for Jupyter rendering)
override-dependencies = [
    "pygame; python_version < '0'",
]
